ALTER TABLE `Config`
    MODIFY COLUMN `ThoiHanTaiLieu` INT NOT NULL DEFAULT 30,
    MODIFY COLUMN `NgayBaoDangKiem` INT NOT NULL DEFAULT 30,
    MODIFY COLUMN `NgayBaoHetHan` INT NOT NULL DEFAULT 30,
    MODIFY COLUMN `SoTabToiDa` INT NOT NULL DEFAULT 7,
    MODIFY COLUMN `ThoiGianBaoSuaChua` INT NOT NULL DEFAULT 30;